version: "3"
services:
  storage:
    image: redis
    volumes:
      - ./counter_micserv/data:/data
  counter:
    image: node:18.17.0
    volumes:
      - ./counter_micserv:/libraryApp/counter_micserv
    working_dir: /libraryApp/counter_micserv
    ports:
      - 3001:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    command: npm run dev
    depends_on:
      - storage
  library:
    image: node:18.17.0
    volumes:
      - ./:/libraryApp
    working_dir: /libraryApp
    ports:
      - 80:3001
    environment:
      - PORT=3001
    command: npm run dev
    depends_on:
      - counter