version: "3"
services:
  storage:
    image: redis
    volumes:
      - ./counter_micserv/data:/data
  counter:
    image: node:18.17.0
    volumes:
      - ./counter_micserv:/libraryApp/counter_micserv
    working_dir: /libraryApp/counter_micserv
    ports:
      - 3001:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    command: npm run dev
    depends_on:
      - storage
  
  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes:
      - ./mongoData:/mongoData
  # mongo-express:
  #   image: mongo-express:0.54.0
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
  #     ME_CONFIG_MONGODB_URL: mongodb://root:12345@mongo:27017/

  library:
    image: node:18.17.0
    volumes:
      - ./:/libraryApp
    working_dir: /libraryApp
    ports:
      - 80:3001
    environment:
      - PORT=3001
      - COUNTER_URL=http://counter
      - MongoURL=mongodb://root:12345@mongodb:27017
      # - MongoURL=mongodb://mongodb:27017
    command: npm run dev
    depends_on:
      - counter
      - mongodb
      # - mongo-express